import { useEffect,useMemo,useState } from "react";
import { open } from "@tauri-apps/plugin-dialog";
import {ArrowLeftRight,Box,Boxes,Camera,FileArchive,FolderOpen,Gamepad2,HardDrive,Power,Rocket,Settings,SlidersHorizontal,TerminalSquare,Sun,Moon,FileSearch,Activity} from "lucide-react";
import {getEngineStatus,startTransfer,pollTransfer,cancelTransfer,listLocalDirectory,createLocalFolder,renameLocalPath,deleteLocalPath,ftpList,ftpCreateFolder,ftpDelete,ftpRename,ftpUpload,ftpDownload,answerTransferPassword,type EngineStatus,type LocalEntry,type RemoteEntry} from "./lib/tauri";
type Tab="transfer"|"ftp"|"files"|"games"|"packages"|"payloads"|"captures"|"power"|"system"|"tools"|"settings";
const tabs:Array<{id:Tab;label:string;icon:any}>=[["transfer","Transfer",ArrowLeftRight],["ftp","FTP Manager",HardDrive],["files","Files",FolderOpen],["games","Games",Gamepad2],["packages","Packages",Box],["payloads","Payloads",Rocket],["captures","Captures",Camera],["power","Power",Power],["system","System",SlidersHorizontal],["tools","Tools",TerminalSquare],["settings","Settings",Settings]].map(([id,label,icon])=>({id:id as Tab,label:label as string,icon}));
const value=(s:any,...keys:string[])=>{for(const k of keys)if(s?.[k]!==undefined&&s?.[k]!==null)return s[k];return null};
function Transfer(){
 const [engine,setEngine]=useState<EngineStatus>({available:false,version:null,detail:"Checking ZSFTP engine..."});
 const [archive,setArchive]=useState(""),[host,setHost]=useState(()=>localStorage.getItem("zerospace-host")??""),[port,setPort]=useState(()=>localStorage.getItem("zerospace-port")??"2121"),[remotePath,setRemotePath]=useState(()=>localStorage.getItem("zerospace-remote")??"/data");
 const [message,setMessage]=useState(""),[running,setRunning]=useState(false),[snapshot,setSnapshot]=useState<any>(null);
 const [logs,setLogs]=useState<string[]>([]);const [password,setPassword]=useState("");const [logCursor,setLogCursor]=useState(0);
 useEffect(()=>{getEngineStatus().then(setEngine).catch(()=>setEngine({available:false,version:null,detail:"ZSFTP engine not installed yet"}))},[]);
 useEffect(()=>{if(!running)return;let stopped=false;let cursor=logCursor;const tick=async()=>{try{const s:any=await pollTransfer(cursor);if(stopped)return;setSnapshot(s);const lines=s?.log?.lines;if(Array.isArray(lines)&&lines.length)setLogs(old=>[...old,...lines.map((x:any)=>`[${x.time??""}] ${String(x.level??"info").toUpperCase()}  ${x.text??""}`)].slice(-1000));if(typeof s?.log?.next==="number"){cursor=s.log.next;setLogCursor(cursor)}if(s?.phase==="finished"){setRunning(false);return}}catch(err){if(!stopped){setMessage(String(err));setRunning(false);return}}if(!stopped)setTimeout(tick,500)};tick();return()=>{stopped=true}},[running]);
 async function chooseArchive(){const selected=await open({multiple:false,directory:false,filters:[{name:"Archives",extensions:["rar","zip","7z"]}]});if(typeof selected==="string")setArchive(selected)}
 async function begin(){setMessage("");setSnapshot(null);setLogs([]);setLogCursor(0);try{setMessage(await startTransfer({archive,host,port:Number(port),directory:remotePath,mode:"passive",user:"",password:"",mkdir:true,verbose:true,bufferMib:Number(localStorage.getItem("zerospace-buffer")??"64")}));setRunning(true)}catch(e){setMessage(String(e))}}
 async function cancel(){try{await cancelTransfer();setMessage("Cancelling transfer…")}catch(e){setMessage(String(e))}}
 const prompt=snapshot?.prompt;const p=snapshot?.progress;const pct=p?.total_bytes?Number(p.sent_bytes??0)/Number(p.total_bytes)*100:0;const current=String(p?.current_file??"Waiting for transfer…");const speed=p?.text?.upload_rate??"—";const eta=p?.text?.eta_total??"—";const memoryRead=p?.text?.unpack_rate??"—";const memorySave=p?.text?.average_rate??"—";const phase=String(snapshot?.phase??(running?"running":"idle"));
 return <div className="page transferPage"><div className="eyebrow">ZEROSPACE · ZSFTP ENGINE</div><h1>Transfer</h1><p className="lead">Stream archive contents directly to your PS5. No full temporary extraction required.</p>
 <div className="badges"><span>RAR</span><span>ZIP</span><span>7Z</span><span className={engine.available?"good":"warn"}>{engine.available?`ZSFTP ${engine.version??""}`:"ZSFTP engine pending"}</span></div>
 <div className="transferLayout"><section className="card setupCard"><div className="sectionTitle"><FileArchive size={18}/> Transfer setup</div>
 <label>Archive<div className="archiveRow"><input value={archive} onChange={e=>setArchive(e.target.value)} placeholder="Choose a .rar, .zip or .7z archive"/><button className="browse" onClick={chooseArchive}><FileSearch size={16}/> Select Archive</button></div></label>
 <div className="grid3"><label>PS5 IP<input value={host} onChange={e=>setHost(e.target.value)} placeholder="192.168.1.50"/></label><label>Port<input value={port} onChange={e=>setPort(e.target.value)}/></label><label>Remote path<input value={remotePath} onChange={e=>setRemotePath(e.target.value)}/></label></div>
 <div className="transferActions"><button className="primary" onClick={begin} disabled={!engine.available||!archive||!host||running}>Start Transfer</button>{running&&<button className="secondary" onClick={cancel}>Cancel</button>}<span className={`phase ${running?"live":""}`}><Activity size={13}/>{phase}</span></div><p className="status">{message||engine.detail}</p></section>
 <section className="card progressCard"><div className="sectionTitle">Transfer status</div><div className="currentFile">{current}</div><div className="progressTrack"><div style={{width:`${Math.max(0,Math.min(100,pct))}%`}}/></div><div className="stats"><div><small>Progress</small><strong>{pct?pct.toFixed(1)+"%":"—"}</strong></div><div><small>Speed</small><strong>{speed??"—"}</strong></div><div><small>ETA</small><strong>{eta}</strong></div><div><small>Memory Read</small><strong>{memoryRead}</strong></div><div><small>Memory Save</small><strong>{memorySave}</strong></div></div></section></div>
 {prompt?.kind==="rar_password"&&<section className="card passwordCard"><div className="sectionTitle">Encrypted archive</div><p>{prompt.error||`${prompt.archive} requires a password.`}</p><div className="passwordRow"><input type="password" value={password} onChange={e=>setPassword(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&password){answerTransferPassword(password);setPassword("")}}} placeholder="RAR password"/><button className="primary" disabled={!password} onClick={()=>{answerTransferPassword(password);setPassword("")}}>Continue</button><button className="secondary" onClick={()=>answerTransferPassword(null)}>Cancel</button></div></section>}<section className="card logCard"><div className="logHead"><div className="sectionTitle"><TerminalSquare size={17}/> Transfer log</div><span>{running?"LIVE":"READY"}</span></div><div className="logWindow">{logs.length?logs.map((line,i)=><div key={i}><b>›</b> {line}</div>):<div className="logEmpty">ZSFTP logs will appear here when a transfer starts.</div>}</div></section></div>
}
function FilesModule(){const [path,setPath]=useState("C:\\");const [items,setItems]=useState<LocalEntry[]>([]);const [error,setError]=useState("");async function load(p=path){try{setItems(await listLocalDirectory(p));setPath(p);setError("")}catch(e){setError(String(e))}}useEffect(()=>{load()},[]);function parent(){const p=path.replace(/[\\\\/]+$/,"");const i=Math.max(p.lastIndexOf("\\\\"),p.lastIndexOf("/"));if(i>=2)load(p.slice(0,i+1))}async function newFolder(){const name=prompt("New folder name");if(name){await createLocalFolder(path.replace(/[\\\\/]+$/,"")+"\\\\"+name);load()}}async function renameItem(x:LocalEntry){const name=prompt("Rename to",x.name);if(name&&name!==x.name){const base=x.path.slice(0,x.path.length-x.name.length);await renameLocalPath(x.path,base+name);load()}}async function remove(x:LocalEntry){if(confirm(`Delete ${x.name}?`)){await deleteLocalPath(x.path);load()}}return <div className="page filesPage"><div className="eyebrow">ZEROSPACE FILES</div><h1>Files</h1><p className="lead">Browse and manage files on this PC. FTP Manager will pair this local pane with your PS5.</p><section className="card fileCard"><div className="fileToolbar"><button className="secondary" onClick={parent}>↑ Up</button><input value={path} onChange={e=>setPath(e.target.value)} onKeyDown={e=>e.key==="Enter"&&load()}/><button className="secondary" onClick={()=>load()}>Refresh</button><button className="secondary" onClick={newFolder}>New Folder</button></div>{error&&<p className="fileError">{error}</p>}<div className="fileTable"><div className="fileHeader"><span>Name</span><span>Size</span><span>Actions</span></div>{items.map(x=><div className="fileRow" key={x.path} onDoubleClick={()=>x.isDir&&load(x.path)}><span>{x.isDir?"▰":"▱"} {x.name}</span><span>{x.isDir?"—":formatBytes(x.size)}</span><span><button onClick={()=>renameItem(x)}>Rename</button><button onClick={()=>remove(x)}>Delete</button></span></div>)}</div></section></div>}
function formatBytes(n:number){if(!n)return "0 B";const u=["B","KB","MB","GB","TB"];const i=Math.min(Math.floor(Math.log(n)/Math.log(1024)),u.length-1);return `${(n/1024**i).toFixed(i?1:0)} ${u[i]}`}
function FtpModule(){
 const [host,setHost]=useState(()=>localStorage.getItem("zerospace-host")??"");const [port,setPort]=useState(()=>localStorage.getItem("zerospace-port")??"2121");const [remote,setRemote]=useState(()=>localStorage.getItem("zerospace-remote")??"/data");
 const [items,setItems]=useState<RemoteEntry[]>([]);const [localPath,setLocalPath]=useState("C:\\");const [localItems,setLocalItems]=useState<LocalEntry[]>([]);const [status,setStatus]=useState("Not connected");const [queue,setQueue]=useState<Array<{id:number,name:string,direction:string,status:string,bytes?:number,localPath?:string,remoteName?:string}>>([]);
 const [localSort,setLocalSort]=useState<"name"|"size">("name"),[remoteSort,setRemoteSort]=useState<"name"|"size">("name");const req=()=>({host,port:Number(port),path:remote});function save(){localStorage.setItem("zerospace-host",host);localStorage.setItem("zerospace-port",port);localStorage.setItem("zerospace-remote",remote)}
 async function loadLocal(path=localPath){try{setLocalItems(await listLocalDirectory(path));setLocalPath(path)}catch(e){setStatus(String(e))}}useEffect(()=>{loadLocal("C:\\")},[]);
 const shownLocal=[...localItems].sort((a,b)=>b.isDir===a.isDir?(localSort==="size"?(b.size??0)-(a.size??0):a.name.localeCompare(b.name)):Number(b.isDir)-Number(a.isDir));const shownRemote=[...items].sort((a,b)=>b.isDir===a.isDir?(remoteSort==="size"?(b.size??0)-(a.size??0):a.name.localeCompare(b.name)):Number(b.isDir)-Number(a.isDir));function localUp(){const p=localPath.replace(/[\\\\/]+$/,"");const i=Math.max(p.lastIndexOf("\\\\"),p.lastIndexOf("/"));if(i>=2)loadLocal(p.slice(0,i+1))}
 async function connect(path=remote){try{setStatus("Connecting…");const r={host,port:Number(port),path};const rows=await ftpList(r);setItems(rows);setRemote(path);save();setStatus(`Connected · ${rows.length} items`)}catch(e){setStatus(String(e))}}
 function up(){const p=remote.replace(/\/$/,"");const i=p.lastIndexOf("/");connect(i<=0?"/":p.slice(0,i))}
 async function mkdir(){const n=prompt("New PS5 folder name");if(n){await ftpCreateFolder(req(),n);connect()}}
 async function rename(x:RemoteEntry){const n=prompt("Rename to",x.name);if(n&&n!==x.name){await ftpRename(req(),x.name,n);connect()}}
 async function remove(x:RemoteEntry){if(confirm(`Delete ${x.name} from PS5?`)){await ftpDelete(req(),x.name,x.isDir);connect()}}
 async function uploadPath(path:string,name:string){const id=Date.now()+Math.random();setQueue(q=>[...q,{id,name,direction:"PC → PS5",status:"Transferring",localPath:path,remoteName:name}]);try{const bytes=await ftpUpload(req(),path,name);setQueue(q=>q.map(x=>x.id===id?{...x,status:"Complete",bytes}:x));connect()}catch(e){setQueue(q=>q.map(x=>x.id===id?{...x,status:"Failed"}:x));setStatus(String(e))}}
 async function uploadPicker(){const p=await open({multiple:false,directory:false});if(typeof p!=="string")return;await uploadPath(p,p.split(/[\\\\/]/).pop()??"upload.bin")}
 async function download(x:RemoteEntry){if(x.isDir)return;const target=localPath.replace(/[\\\\/]+$/,"")+"\\\\"+x.name;const id=Date.now()+Math.random();setQueue(q=>[...q,{id,name:x.name,direction:"PS5 → PC",status:"Transferring",localPath:target,remoteName:x.name}]);try{const bytes=await ftpDownload(req(),x.name,target);setQueue(q=>q.map(y=>y.id===id?{...y,status:"Complete",bytes}:y));loadLocal()}catch(e){setQueue(q=>q.map(y=>y.id===id?{...y,status:"Failed"}:y));setStatus(String(e))}}
 return <div className="page"><div className="eyebrow">ZEROSPACE FTP MANAGER</div><h1>FTP Manager</h1><p className="lead">Dual-pane file manager for moving files directly between this PC and your PS5.</p>
 <section className="card connectionBar"><label>PS5 IP<input value={host} onChange={e=>setHost(e.target.value)} placeholder="192.168.1.50"/></label><label>Port<input value={port} onChange={e=>setPort(e.target.value)}/></label><label>Remote path<input value={remote} onChange={e=>setRemote(e.target.value)}/></label><button className="primary" onClick={()=>connect()}>Connect</button></section><div className="ftpStatus">{status}</div>
 <section className="ftpPreview"><div className="card pane remotePane"><div className="paneTitle">This PC <span>LOCAL</span></div><div className="remoteTools"><button onClick={localUp}>↑ Up</button><button onClick={()=>loadLocal()}>Refresh</button><button onClick={uploadPicker}>Choose Upload</button><button onClick={()=>setLocalSort(s=>s==="name"?"size":"name")}>Sort: {localSort}</button></div><div className="localPathBar"><input value={localPath} onChange={e=>setLocalPath(e.target.value)} onKeyDown={e=>e.key==="Enter"&&loadLocal()}/></div><div className="remoteList">{shownLocal.map(x=><div className="remoteRow" key={x.path} onDoubleClick={()=>x.isDir&&loadLocal(x.path)}><span>{x.isDir?"▰":"▱"} {x.name}</span><span>{x.isDir?"—":formatBytes(x.size)}</span><span>{!x.isDir&&<button onClick={()=>uploadPath(x.path,x.name)}>Upload →</button>}</span></div>)}</div></div>
 <div className="ftpArrows">⇄</div><div className="card pane remotePane"><div className="paneTitle">PS5 <span>FTP</span></div><div className="remoteTools"><button onClick={up}>↑ Up</button><button onClick={()=>connect()}>Refresh</button><button onClick={mkdir}>New Folder</button><button onClick={uploadPicker}>Upload</button><button onClick={()=>setRemoteSort(s=>s==="name"?"size":"name")}>Sort: {remoteSort}</button></div><div className="remotePath">{remote}</div><div className="remoteList">{shownRemote.map(x=><div className="remoteRow" key={x.path} onDoubleClick={()=>x.isDir&&connect(x.path)}><span>{x.isDir?"▰":"▱"} {x.name}</span><span>{x.isDir?"—":formatBytes(x.size??0)}</span><span><button onClick={()=>rename(x)}>Rename</button><button onClick={()=>remove(x)}>Delete</button>{!x.isDir&&<button onClick={()=>download(x)}>← Download</button>}</span></div>)}</div></div></section>
 <section className="card queueCard"><div className="paneTitle">Transfer Queue <span>{queue.length} ITEMS</span></div>{queue.length===0?<div className="queueEmpty">Uploads and downloads will appear here.</div>:<div className="queueList">{queue.map(q=><div className="queueRow" key={q.id}><span>{q.direction}</span><strong>{q.name}</strong><span>{q.bytes?formatBytes(q.bytes):"—"}</span><em>{q.status}</em><span className="queueActions">{q.status==="Failed"&&q.localPath&&q.remoteName&&<button onClick={()=>{setQueue(old=>old.filter(x=>x.id!==q.id));q.direction==="PC → PS5"?uploadPath(q.localPath!,q.remoteName!):ftpDownload(req(),q.remoteName!,q.localPath!).then(bytes=>setQueue(old=>[...old,{...q,id:Date.now(),status:"Complete",bytes}])).catch(e=>setStatus(String(e)))}}>Retry</button>}<button onClick={()=>setQueue(old=>old.filter(x=>x.id!==q.id))}>Remove</button></span></div>)}</div>}</section></div>
}
function SettingsModule(){const [host,setHost]=useState(()=>localStorage.getItem("zerospace-host")??"");const [port,setPort]=useState(()=>localStorage.getItem("zerospace-port")??"2121");const [remote,setRemote]=useState(()=>localStorage.getItem("zerospace-remote")??"/data");const [buffer,setBuffer]=useState(()=>localStorage.getItem("zerospace-buffer")??"64");const [saved,setSaved]=useState(false);function save(){localStorage.setItem("zerospace-host",host);localStorage.setItem("zerospace-port",port);localStorage.setItem("zerospace-remote",remote);localStorage.setItem("zerospace-buffer",buffer);setSaved(true);setTimeout(()=>setSaved(false),1200)}return <div className="page"><div className="eyebrow">ZEROSPACE SETTINGS</div><h1>Settings</h1><p className="lead">Shared defaults used across Transfer and FTP Manager.</p><section className="card settingsCard"><div className="sectionTitle">PS5 connection</div><div className="grid3"><label>PS5 IP<input value={host} onChange={e=>setHost(e.target.value)} placeholder="192.168.1.50"/></label><label>Port<input value={port} onChange={e=>setPort(e.target.value)}/></label><label>Default remote path<input value={remote} onChange={e=>setRemote(e.target.value)}/></label></div><div className="sectionTitle settingsSub">Transfer engine</div><label className="shortField">Memory buffer (MiB)<input value={buffer} onChange={e=>setBuffer(e.target.value)}/></label><div className="settingsActions"><button className="primary" onClick={save}>Save Settings</button>{saved&&<span>Saved</span>}</div></section></div>}
function Module({tab,title}:{tab:Tab;title:string}){if(tab==="files")return <FilesModule/>;if(tab==="ftp")return <FtpModule/>;if(tab==="settings")return <SettingsModule/>;const copy:Record<string,string>={games:"Installed-game library and metadata tools.",packages:"PKG queue and package management workspace.",payloads:"Payload library and launch workspace.",captures:"Browse and export PS5 captures.",power:"PS5 power and session controls.",system:"Console information and system utilities.",tools:"Focused utilities that do not belong in the main modules."};return <div className="page"><div className="eyebrow">ZEROSPACE MODULE</div><h1>{title}</h1><section className="card empty"><Boxes size={30}/><h2>{title}</h2><p>{copy[tab]??"ZeroSpace module."}</p></section></div>}
export default function App(){const [active,setActive]=useState<Tab>("transfer");const [theme,setTheme]=useState<"dark"|"light">(()=>localStorage.getItem("zerospace-theme")==="light"?"light":"dark");useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem("zerospace-theme",theme)},[theme]);const current=useMemo(()=>tabs.find(t=>t.id===active)!,[active]);return <div className="shell"><aside><div className="brand"><div className="brandGlyph">Z</div><div><strong>ZeroSpace</strong><small>PS5 Toolkit</small></div></div><nav>{tabs.map(t=>{const Icon=t.icon;return <button key={t.id} className={active===t.id?"active":""} onClick={()=>setActive(t.id)}><Icon size={18}/><span>{t.label}</span></button>})}</nav><div className="sideFoot">Windows x64 · Early Development</div></aside><main><div className="topCorner"><div className="orbitBuddy" aria-hidden="true"><span>••</span></div><button className="themeToggle" onClick={()=>setTheme(theme==="dark"?"light":"dark")} title={`Switch to ${theme==="dark"?"light":"dark"} mode`}>{theme==="dark"?<Sun size={17}/>:<Moon size={17}/>}</button></div>{active==="transfer"?<Transfer/>:<Module tab={active} title={current.label}/>}</main></div>}